#!/bin/sh
echo Building...
go build -v ./...
echo Vet...
go vet ./... > govet.out
echo Test...
go test ./... -coverprofile=coverage.out -json > gotest.json
echo Sonar...
/d/sys/sonar-scanner-4.2.0.1873-windows/bin/sonar-scanner.bat
